website/website/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using database.Models;
using website.Models.Interfaces;
using Microsoft.AspNetCore.Authorization;
using website.Models;

namespace website.Controllers
{
    public class ProfileController : Controller
    {
        private UserManager<User> userManager;
        private SignInManager<User> signInManager;
        private IUMDBRepository db;
        public ProfileController(IUMDBRepository _db, UserManager<User> _userManager, SignInManager<User> _signInManager)
        {
            userManager = _userManager;
            signInManager = _signInManager;
            db = _db;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(UserRegisterModel registerModel)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    UserName = registerModel.UserName,
                    Email = registerModel.Email,
                    Name = registerModel.Name
                };
                IdentityResult result = await userManager.CreateAsync(user, registerModel.Password);
                if (result.Succeeded)
                {
                    Microsoft.AspNetCore.Identity.SignInResult result1 = await signInManager.PasswordSignInAsync(user, registerModel.Password, false, false);
                    return RedirectToAction("Query", "Search");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(registerModel);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(UserLoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                User user = await userManager.FindByNameAsync(loginModel.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, loginModel.Password, false, false);
                    return RedirectToAction("Query", "Search");
                }
                else
                {
                    ModelState.AddModelError(nameof(UserLoginModel.UserName), "Неправильне і'мя користувача чи пароль!");
                }
            }
            return View(loginModel);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Query","Search");
        }
    }
}

website/website/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using database.Models;
using website.Models.Interfaces;
using Microsoft.EntityFrameworkCore;
using website.Models;
using Microsoft.AspNetCore.Identity;

namespace website.Controllers
{
    public class SearchController : Controller
    {
        private UserManager<User> userManager;
        private readonly IUMDBRepository db;
        public SearchController(IUMDBRepository _db, UserManager<User> _userManager)
        {
            db = _db;
            userManager = _userManager;
        }

        public IActionResult Query(int country=0, int[] genres = null, string orderBy="year-desc", int yearFrom=1920, int yearTo=2018, string movieName="", int page = 1)
        {
            IQueryable<Movie> allMovies = db.Movies
                                          .Include(m => m.Countries).ThenInclude(c => c.Country)
                                          .Include(m => m.Genres).ThenInclude(g => g.Genre);
            int perPage = 20;
            if (country!=0)
            {
                allMovies = allMovies.Where(m => m.Countries.Any(p => p.Country.Id == country));
            }
            if(movieName!=null && movieName!="")
            {
                allMovies = allMovies.Where(m => m.Name.Contains(movieName));
            }
            if(genres!=null && genres.Length!=0)
            {
                allMovies = allMovies.Where(m => m.Genres.Where(g => genres.Contains(g.Genre.Id)).Count() != 0);
            }
            if(orderBy == "year-desc")
            {
                allMovies = allMovies.OrderByDescending(m => m.Year);
            }
            else if(orderBy == "year-asc")
            {
                allMovies = allMovies.OrderBy(m => m.Year);
            }
            if(yearFrom>1920)
            {
                allMovies = allMovies.Where(m => m.Year >= yearFrom);
            }
            if(yearTo<2018)
            {
                allMovies = allMovies.Where(m => m.Year <= yearTo);
            }
            return View(new SearchViewModel(db.Genres, 
                                            db.Countries,
                                            allMovies.Count(),
                                            allMovies.Skip(page*perPage-perPage).Take(perPage),
                                            genres,
                                            country,
                                            orderBy,
                                            yearFrom,
                                            yearTo,
                                            movieName,
                                            new PagingInfo
                                            {
                                                CurrentPage = page,
                                                ItemsPerPage = perPage,
                                                TotalItems = allMovies.Count()
                                            }));
        }
    }
}

website/website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UMDB</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Навігація</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Search" asp-action="Query" class="navbar-brand">UMDB</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="float:unset;">
                    <li><a asp-area="" asp-controller="Search" asp-action="Query">Головна</a></li>
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li style="float:right;"><a asp-area="" asp-controller="Profile" asp-action="Logout" style="float:right;">Вихід</a></li>
                        <li style="float:right;"><a asp-area="" asp-controller="Profile" asp-action="ViewProfile" asp-route-name="@User?.Identity?.Name" style="float:right;">@User?.Identity?.Name</a></li>
                    }
                    else
                    {
                        <li style="float:right;"><a asp-area="" asp-controller="Profile" asp-action="Login" style="float:right;">Вхід</a></li>
                        <li style="float:right;"><a asp-area="" asp-controller="Profile" asp-action="Register" style="float:right;">Реєстрація</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Українська база даних фільмів</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>